########################################################################
# Formality Verification Script generated by:
#     fm_mk_script -o formality_auto.tcl "../reports/default.svf"
# Formality (R)  Version X-2025.06-SP3 -- Oct 13, 2025
# Copyright 2007-2026 Synopsys, Inc. All rights reserved.
########################################################################

########################################################################
# Synopsys Auto Setup Mode
########################################################################

set synopsys_auto_setup true

# Note - The Synopsys Auto Setup mode is less conservative than the
# Formality default mode, and is more likely to result in a successful
# verification out-of-the-box.
#
# Setting synopsys_auto_setup will change the values of the variables
# listed here below.  You may change any of these variables back to
# their default settings to be more conservative.  Uncomment the
# appropriate lines below to revert back to their default settings:

      # set hdlin_ignore_parallel_case true
      # set hdlin_ignore_full_case true
      # set verification_verify_directly_undriven_output true
      # set hdlin_ignore_embedded_configuration false
      # set svf_ignore_unqualified_fsm_information true

########################################################################
# Specify number of processes on the local machine to use in parallel
# Default is 1 core
########################################################################

#set_host_options -max_cores 4

########################################################################
# Distributed Processing
#
# Uncomment the following line to enable distributed processing.
# Modify the arguments to the command to match your compute farm.
# See "man set_dpx_options" for details.
########################################################################

# set_dpx_options \
    -protocol <PROTOCOL> \
    -submit_command <COMMAND> \
    -max_workers <NUMBER> \
    -max_cores <NUMBER>     

########################################################################
# Setup for instantiated or function-inferred DesignWare components
########################################################################

set hdlin_dwroot /Tools/synopsys/syn/X-2025.06-SP2

########################################################################
# Search path
########################################################################

set search_path " \
	/home/ana.meira/ci-expert/vending_machine_rtl-master \
	/home/ana.meira/ci-expert/vending_machine_rtl-master/rtl \
	/home/ana.meira/ci-expert/vending_machine_rtl-master/libs \
	/home/ana.meira/ci-expert/vending_machine_rtl-master/libs "

########################################################################
# Read in the SVF file(s)
########################################################################

set_svf reports/default.svf

########################################################################
# Read in the libraries
########################################################################

read_db -technology_library /home/ana.meira/ci-expert/vending_machine_rtl-master/libs/saed32rvt_tt1p05v25c.db


########################################################################
########################################################################

# set link_library " * dw_foundation.sldb saed32rvt_tt1p05v25c.db "

########################################################################
# Read in the Reference Design as verilog/vhdl source code
########################################################################

set hdlin_sverilog_std 2017
set hdlin_vhdl_std 2008
set hdlin_vrlg_std 2005
read_sverilog -r -libname WORK  \
	rtl/vending_pkg.sv
read_sverilog -r -libname WORK  \
	rtl/vending_top.sv
read_sverilog -r -libname WORK  \
	rtl/control_unit.sv
read_sverilog -r -libname WORK  \
	rtl/comparator.sv
read_sverilog -r -libname WORK  \
	rtl/credit_reg.sv
read_sverilog -r -libname WORK  \
	rtl/memory.sv
read_sverilog -r -libname WORK  \
	rtl/subtractor.sv
set_top r:/WORK/vending_top


########################################################################
# Read in the Implementation Design created from DC
#
# Choose the file that you wish to verify
########################################################################

# USER INTERVENTION REQUIRED HERE:
read_verilog -i /home/ana.meira/ci-expert/vending_machine_rtl-master/synth/vending_syn.v
# read_ddc -i /home/ana.meira/ci-expert/vending_machine_rtl-master/synth/vending_syn.ddc
# read_ddc -i /home/ana.meira/ci-expert/vending_machine_rtl-master/synth/vending.ddc
set_top i:/WORK/vending_top


# 6. Casamento de pontos entre golden e revised, usando o guidance do SVF
match

# 7. Prova de equivalência ponto a ponto
verify

# 8. Relatórios de sign-off
redirect -file fm/reports/formality_status.rpt { report_status }
report_passing_points > fm/reports/formality_passing.rpt
report_failing_points > fm/reports/formality_failing.rpt
report_unmatched_points > fm/reports/formality_unmatched.rpt

# ------------------------------------------------------------
# Relatórios ACOMPANHAMENTO
# ------------------------------------------------------------

# Salva os relatórios na nova pasta
report_svf_operation -status accepted > fm/reports/formality_svf_accepted.rpt
report_svf_operation -status rejected > fm/reports/formality_svf_rejected.rpt

report_matched_points > fm/reports/formality_matched.rpt
report_unmatched_points > fm/reports/formality_unmatched.rpt

report_passing_points > fm/reports/formality_pass.rpt
report_failing_points > fm/reports/formality_fail.rpt

# Descomente a linha abaixo para o Formality fechar sozinho quando terminar
exit



