###################################################################

# Created by write_sdc on Fri Jul 17 14:27:46 2026

###################################################################
set sdc_version 2.2

set_units -time ns -resistance MOhm -capacitance fF -voltage V -current uA
set_max_fanout 8 [current_design]
set_driving_cell -lib_cell NBUFFX4_RVT -pin Y [get_ports rst]
set_driving_cell -lib_cell NBUFFX4_RVT -pin Y [get_ports cancel]
set_driving_cell -lib_cell NBUFFX4_RVT -pin Y [get_ports confirm]
set_driving_cell -lib_cell NBUFFX4_RVT -pin Y [get_ports {sell_item[1]}]
set_driving_cell -lib_cell NBUFFX4_RVT -pin Y [get_ports {sell_item[0]}]
set_driving_cell -lib_cell NBUFFX4_RVT -pin Y [get_ports {coin_in[1]}]
set_driving_cell -lib_cell NBUFFX4_RVT -pin Y [get_ports {coin_in[0]}]
set_load -pin_load 5.46271 [get_ports dispense]
set_load -pin_load 5.46271 [get_ports error]
set_load -pin_load 5.46271 [get_ports {change_out[7]}]
set_load -pin_load 5.46271 [get_ports {change_out[6]}]
set_load -pin_load 5.46271 [get_ports {change_out[5]}]
set_load -pin_load 5.46271 [get_ports {change_out[4]}]
set_load -pin_load 5.46271 [get_ports {change_out[3]}]
set_load -pin_load 5.46271 [get_ports {change_out[2]}]
set_load -pin_load 5.46271 [get_ports {change_out[1]}]
set_load -pin_load 5.46271 [get_ports {change_out[0]}]
set_load -pin_load 5.46271 [get_ports {display[7]}]
set_load -pin_load 5.46271 [get_ports {display[6]}]
set_load -pin_load 5.46271 [get_ports {display[5]}]
set_load -pin_load 5.46271 [get_ports {display[4]}]
set_load -pin_load 5.46271 [get_ports {display[3]}]
set_load -pin_load 5.46271 [get_ports {display[2]}]
set_load -pin_load 5.46271 [get_ports {display[1]}]
set_load -pin_load 5.46271 [get_ports {display[0]}]
set_load -pin_load 5.46271 [get_ports {state_out[2]}]
set_load -pin_load 5.46271 [get_ports {state_out[1]}]
set_load -pin_load 5.46271 [get_ports {state_out[0]}]
create_clock [get_ports clk]  -period 6  -waveform {0 3}
set_clock_uncertainty 0.5  [get_clocks clk]
set_clock_transition -max -rise 0.1 [get_clocks clk]
set_clock_transition -max -fall 0.1 [get_clocks clk]
set_clock_transition -min -rise 0.1 [get_clocks clk]
set_clock_transition -min -fall 0.1 [get_clocks clk]
set_input_delay -clock clk  3  [get_ports rst]
set_input_delay -clock clk  3  [get_ports cancel]
set_input_delay -clock clk  3  [get_ports confirm]
set_input_delay -clock clk  3  [get_ports {sell_item[1]}]
set_input_delay -clock clk  3  [get_ports {sell_item[0]}]
set_input_delay -clock clk  3  [get_ports {coin_in[1]}]
set_input_delay -clock clk  3  [get_ports {coin_in[0]}]
set_output_delay -clock clk  3  [get_ports dispense]
set_output_delay -clock clk  3  [get_ports error]
set_output_delay -clock clk  3  [get_ports {change_out[7]}]
set_output_delay -clock clk  3  [get_ports {change_out[6]}]
set_output_delay -clock clk  3  [get_ports {change_out[5]}]
set_output_delay -clock clk  3  [get_ports {change_out[4]}]
set_output_delay -clock clk  3  [get_ports {change_out[3]}]
set_output_delay -clock clk  3  [get_ports {change_out[2]}]
set_output_delay -clock clk  3  [get_ports {change_out[1]}]
set_output_delay -clock clk  3  [get_ports {change_out[0]}]
set_output_delay -clock clk  3  [get_ports {display[7]}]
set_output_delay -clock clk  3  [get_ports {display[6]}]
set_output_delay -clock clk  3  [get_ports {display[5]}]
set_output_delay -clock clk  3  [get_ports {display[4]}]
set_output_delay -clock clk  3  [get_ports {display[3]}]
set_output_delay -clock clk  3  [get_ports {display[2]}]
set_output_delay -clock clk  3  [get_ports {display[1]}]
set_output_delay -clock clk  3  [get_ports {display[0]}]
set_output_delay -clock clk  3  [get_ports {state_out[2]}]
set_output_delay -clock clk  3  [get_ports {state_out[1]}]
set_output_delay -clock clk  3  [get_ports {state_out[0]}]
